<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Services\FileManager' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Services/FileManager.php';

return $this->services['AppBundle\Services\FileManager'] = new \AppBundle\Services\FileManager($this);
