<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.d6sovxk' shared service.

return $this->services['service_locator.d6sovxk'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('fileManager' => function () {
    $f = function (\AppBundle\Services\FileManager $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Services\FileManager']) ? $this->services['AppBundle\Services\FileManager'] : $this->services['AppBundle\Services\FileManager'] = new \AppBundle\Services\FileManager($this)) && false ?: '_'});
}));
