<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2vwqx9i\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2vwqx9i/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/Container2vwqx9i.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\Container2vwqx9i\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \Container2vwqx9i\appTestDebugProjectContainer(array(
    'container.build_hash' => '2vwqx9i',
    'container.build_id' => '579a7c72',
    'container.build_time' => 1543592134,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2vwqx9i');
