<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXixgcfw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXixgcfw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXixgcfw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXixgcfw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXixgcfw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xixgcfw',
    'container.build_id' => 'cb20db8c',
    'container.build_time' => 1543594452,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXixgcfw');
